### ISSUE TITLE
Add support for Billund municipality

### ISSUE THREAD

**Issue by Epenance** [briis/pyrenoweb#8]
As far as I can tell Renoweb has support for Billund, but it doesn't seem to be added to the municipality list in this wrapper. 

It would be nice to have it supported, not sure if there is any particular reasons its not currently.

**Comment by Epenance** [comment]
Maybe added a fix here: https://github.com/briis/pyrenoweb/pull/9

**Comment by briis** [comment]
Du har ret. Jeg testede alle kommuner, men har senere fundet at nogle få, smuttede for mig. Billund ser ud til at være supporteret. Jeg laver lige en endelig test, så merger jeg den Pull Request

**Comment by briis** [comment]
Billund er nu lagt ind og testet. Der var lidt ekstr tilretninger der skulle til før det virkede, grundet navngivning af containere.

**Comment by Epenance** [comment]
Fedt, hvornår er der planer om en release? :)
